# Site settings
title: '#_ Terminal Root'
email: terminalroot.com.br@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog GNU/Linux, Shell Script Bash, Debian, Linguagens de Desenvolvimento, Contabilidade, Servidores, Web, Mobile e Games.

twitter_username: terminalrootsh
github_username:  terminalrootsh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: LPI
    url: /lpi
  - title: Tags
    url: /tags
  - title: Parceiros
    url: /parceiros
  - title: Mais
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
