# Site settings
title: 'Terminal Root'
email: terminalroot.com.br@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog GNU/Linux, Shell Script Bash, Debian, Linguagens de Desenvolvimento, Contabilidade, Servidores, Web, Mobile e Games.

twitter_username: terminalroottv
github_username:  terminalrootsh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Cursos
    url: /cursos
  - title: Tags
    url: /tags
  - title: Quiz
    url: /quiz
  - title: LPI
    url: /lpi
  - title: Parceiros
    url: /parceiros

collections:
  - cursos
  
gems:
  - jekyll-seo-tag

title: Terminal Root - Blog Linux, Blog Shell Script Bash, Desenvolvimento e Web.
description: Blog GNU/Linux, Shell Script Bash, Debian, Linguagens de Desenvolvimento, Contabilidade, Servidores, Web, Mobile e Games.
url: www.terminalroot.com.br
author: Terminal Root
social:
  name: Terminal Root
  links:
    - https://twitter.com/TerminalRootTV
    - https://www.facebook.com/TerminalRoot
    - https://www.youtube.com/TerminalRootTV
    - https://plus.google.com/+TerminalRootTV
    - https://github.com/terminalrootsh
google_site_verification: zMxWGsmS5xlxc71KSaJx77T6CfB4bP3hdO_v5qfAsuY


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
